version: '3.8'

services:
  # Backend Spring Boot Service
  backend:
    build:
      context: ./backend1 # Le répertoire contenant le Dockerfile pour Spring Boot
      dockerfile: Dockerfile
    container_name: backend1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Calmify
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_SQL_INIT_PLATFORM=postgresql
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  # Frontend React Service
  frontend:
    build:
      context: ./front # Le répertoire contenant le Dockerfile pour React
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  # NLP Python Service
  nlp:
    build:
      context: ./NLP # Le répertoire contenant le Dockerfile pour Python NLP
      dockerfile: Dockerfile
    container_name: nlp
    ports:
      - "5000:5000" # Port pour l'API NLP si elle est exposée
    networks:
      - app-network

  # PostgreSQL Database Service
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Calmify
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
